In [1]:
import pandas as pd
import numpy as np

In [2]:
data=r"C:\Users\shafqat Ali\Downloads\Video_Game_Sales.xlsx"

In [3]:
df=pd.read_excel(data)

In [4]:
df.head()

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
0,GM100000,Dragon Realm,2021-04-24,PC,Racing,Take-Two Interactive,Iron Wolf,Japan,E10+,Subscription,0.58,48.97,66.8,6.6,97.0,9.43
1,GM100001,Football Pro,2024-06-24,Nintendo Switch,Shooter,Bandai Namco,Blue Horizon,Latin America,M,Subscription,3.28,52.94,23.3,5.6,87.0,133.18
2,GM100002,Zombie Outbreak,2017-03-05,PC,Adventure,Square Enix,Pixel Forge,Latin America,T,Retail,0.23,25.23,39.5,8.2,80.0,3.51
3,GM100003,Space Colony,2017-08-10,Xbox Series X,Adventure,Activision,Red Dragon Studios,Europe,T,Digital Store,3.35,72.40,57.1,6.0,98.0,104.05
4,GM100004,Shadow Protocol,2020-10-26,Mobile,Action,Square Enix,Digital Realm,Europe,M,Digital Store,11.67,10.32,13.6,5.1,40.0,104.06

In [5]:
r,c=df.shape
print(f'''this dataset contains
Rows:{r}
col:{c}''')

this dataset contains
Rows:10000
col:16

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Game_ID           10000 non-null  object
 1   Game_Title        10000 non-null  object
 2   Release_Date      9880 non-null   datetime64[ns]
 3   Platform          10000 non-null  object
 4   Genre             9921 non-null   object
 5   Publisher         9900 non-null   object
 6   Developer         10000 non-null  object
 7   Region            10000 non-null  object
 8   Age_Rating        10000 non-null  object
 9   Sales_Channel     10000 non-null  object
 10  Units_Sold_M      10000 non-null  float64
 11  Avg_Price_USD     10000 non-null  float64
 12  Discount_Pct      10000 non-null  float64
 13  User_Score        9850 non-null   float64
 14  Metacritic_Score  9900 non-null   float64
 15  Global_Revenue_M  10000 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(9)
memory usage: 1.2+ MB

In [7]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Game_ID,10000,9950,GM100042,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Game_Title,10000,20,Mystic Quest,554,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Release_Date,9880,NaN,NaN,NaN,2020-06-25 12:48:23.319838208,2015-01-01 00:00:00,2017-10-08 00:00:00,2020-06-21 00:00:00,2023-03-10 06:00:00,2025-12-31 00:00:00,NaN
Platform,10000,10,PC,1294,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Genre,9921,12,Racing,1039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Publisher,9900,11,Activision,954,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Developer,10000,10,Blue Horizon,1040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Region,10000,6,North America,1735,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age_Rating,10000,5,M,2044,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sales_Channel,10000,6,Retail,2036,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Units_Sold_M,10000.0,NaN,NaN,NaN,2.054775,0.01,0.58,1.19,2.4,179.21,3.280232
Avg_Price_USD,10000.0,NaN,NaN,NaN,45.008505,9.99,27.41,45.07,62.8,79.99,20.18591
Discount_Pct,10000.0,NaN,NaN,NaN,35.24624,0.0,17.9,35.1,52.7,125.0,20.357817
User_Score,9850.0,NaN,NaN,NaN,6.004406,2.0,4.0,6.0,8.0,15.0,2.326646
Metacritic_Score,9900.0,NaN,NaN,NaN,66.359192,35.0,50.0,66.0,82.0,110.0,18.599698
Global_Revenue_M,10000.0,NaN,NaN,NaN,60.356968,-143.81,12.62,29.03,66.215,5657.8,114.072012

In [8]:
df.isnull().sum()

Game_ID               0
Game_Title            0
Release_Date        120
Platform              0
Genre                79
Publisher           100
Developer             0
Region                0
Age_Rating            0
Sales_Channel         0
Units_Sold_M          0
Avg_Price_USD         0
Discount_Pct          0
User_Score          150
Metacritic_Score    100
Global_Revenue_M      0
dtype: int64

In [9]:
df.dtypes

Game_ID                     object
Game_Title                  object
Release_Date        datetime64[ns]
Platform                    object
Genre                       object
Publisher                   object
Developer                   object
Region                      object
Age_Rating                  object
Sales_Channel               object
Units_Sold_M               float64
Avg_Price_USD              float64
Discount_Pct               float64
User_Score                 float64
Metacritic_Score           float64
Global_Revenue_M           float64
dtype: object

In [10]:
df['Release_Date']=pd.to_datetime(df['Release_Date'])

In [11]:
df[df.duplicated(keep=False)]

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
42,GM100042,Dark Empire,2020-02-06,Xbox Series X,Adventure,Bandai Namco,Blue Horizon,Asia-Pacific,RP,Digital Store,3.27,73.43,3.0,8.7,79.0,232.91
177,GM100177,Dark Empire,2022-05-07,PC,Puzzle,Microsoft,Iron Wolf,Europe,T,Online Marketplace,8.71,33.83,46.8,7.4,63.0,156.76
418,GM100418,Ninja Legacy,2016-06-20,PS5,Racing,SEGA,Red Dragon Studios,Japan,T,Digital Store,1.69,49.63,34.6,8.5,40.0,54.85
438,GM100438,Ninja Legacy,2024-04-09,Xbox One,Puzzle,Microsoft,Quantum Works,North America,E,Digital Store,0.35,62.92,56.1,9.4,64.0,9.67
533,GM100533,Racing Horizon,2020-01-15,PC,Shooter,Activision,Quantum Works,Middle East & Africa,RP,Retail,5.52,55.99,22.5,9.1,43.0,239.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,GM107872,Football Pro,2016-12-30,Nintendo Switch,Puzzle,Microsoft,Quantum Works,Japan,T,Digital Store,1.43,49.98,18.7,6.1,58.0,58.11
9996,GM100533,Racing Horizon,2020-01-15,PC,Shooter,Activision,Quantum Works,Middle East & Africa,RP,Retail,5.52,55.99,22.5,9.1,43.0,239.53
9997,GM109895,Tactical Strike,2019-09-16,Mobile,Shooter,SEGA,NextGen Labs,North America,RP,Digital Store,0.35,16.20,22.1,2.7,83.0,4.42
9998,GM107494,Cyber Frontier,2019-06-15,Mobile,RPG,Microsoft,Red Dragon Studios,North America,M,Retail,0.34,38.16,6.6,5.9,55.0,12.12
9999,GM105747,Tactical Strike,2022-05-27,PC,Action,Activision,Quantum Works,Middle East & Africa,M,Retail,0.40,16.89,40.0,4.2,92.0,4.05

In [12]:
df.drop_duplicates()

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
0,GM100000,Dragon Realm,2021-04-24,PC,Racing,Take-Two Interactive,Iron Wolf,Japan,E10+,Subscription,0.58,48.97,66.8,6.6,97.0,9.43
1,GM100001,Football Pro,2024-06-24,Nintendo Switch,Shooter,Bandai Namco,Blue Horizon,Latin America,M,Subscription,3.28,52.94,23.3,5.6,87.0,133.18
2,GM100002,Zombie Outbreak,2017-03-05,PC,Adventure,Square Enix,Pixel Forge,Latin America,T,Retail,0.23,25.23,39.5,8.2,80.0,3.51
3,GM100003,Space Colony,2017-08-10,Xbox Series X,Adventure,Activision,Red Dragon Studios,Europe,T,Digital Store,3.35,72.40,57.1,6.0,98.0,104.05
4,GM100004,Shadow Protocol,2020-10-26,Mobile,Action,Square Enix,Digital Realm,Europe,M,Digital Store,11.67,10.32,13.6,5.1,40.0,104.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9945,GM109945,Football Pro,2023-06-20,Nintendo Switch,Racing,Square Enix,Red Dragon Studios,Europe,RP,Retail,0.37,64.61,32.4,9.6,82.0,16.16
9946,GM109946,City Builder X,2019-01-27,Steam Deck,Strategy,Nintendo,Blue Horizon,North America,E,Retail,1.37,30.89,1.9,4.5,90.0,41.52
9947,GM109947,Tactical Strike,2023-08-24,PS5,Racing,Electronic Arts,Quantum Works,Latin America,RP,Retail,0.17,43.82,11.7,9.7,58.0,6.58
9948,GM109948,Ocean Explorer,2023-08-30,Xbox One,Strategy,Take-Two Interactive,Vertex Studio,Japan,T,Retail,1.50,26.13,68.3,7.7,70.0,12.42
9949,GM109949,Ninja Legacy,2024-04-13,PC,Strategy,Ubisoft,Iron Wolf,Middle East & Africa,E10+,Retail,1.85,73.34,41.7,9.1,48.0,79.10

In [13]:
print(df['Release_Date'].dtype)

datetime64[ns]

In [14]:
print(df["Platform"].value_counts(dropna=False))

Platform
PC                 1294
Nintendo Switch    1260
Steam Deck         1254
PS5                1251
Xbox One           1247
PS4                1233
Xbox Series X      1216
Mobile             1166
 PS5                 40
ps5                  39
Name: count, dtype: int64

In [15]:
df["Platform"] = df["Platform"].str.strip().str.title()

In [16]:
print(df["Platform"].value_counts(dropna=False))

Platform
Ps5                1330
Pc                 1294
Nintendo Switch    1260
Steam Deck         1254
Xbox One           1247
Ps4                1233
Xbox Series X      1216
Mobile             1166
Name: count, dtype: int64

In [17]:
 df["Game_ID"].value_counts(dropna=False)

Game_ID
GM100042    2
GM100533    2
GM100870    2
GM102958    2
GM101726    2
           ..
GM109929    1
GM109930    1
GM109931    1
GM109932    1
GM100013    1
Name: count, Length: 9950, dtype: int64

In [18]:
df["Game_ID"]=df["Game_ID"].str.strip().str.title()

In [19]:
df["Game_ID"].value_counts(dropna=False)

Game_ID
Gm100042    2
Gm100533    2
Gm100870    2
Gm102958    2
Gm101726    2
           ..
Gm109929    1
Gm109930    1
Gm109931    1
Gm109932    1
Gm100013    1
Name: count, Length: 9950, dtype: int64

In [20]:
df["Game_Title"].value_counts(dropna=False)

Game_Title
Mystic Quest       554
Racing Horizon     542
Kingdom Reborn     526
Dark Empire        523
Zombie Outbreak    517
Shadow Protocol    515
Ninja Legacy       508
City Builder X     503
Ocean Explorer     503
Neon Drift         499
Street Legends     498
Galaxy Raiders     490
Battle Arena       488
Space Colony       485
Warzone Echo       482
Cyber Frontier     482
Football Pro       478
Fantasy League     474
Dragon Realm       469
Tactical Strike    464
Name: count, dtype: int64

In [21]:
df["Game_Title"]=df["Game_Title"].str.strip().str.title()

In [22]:
df["Game_Title"].value_counts(dropna=False)

Game_Title
Mystic Quest       554
Racing Horizon     542
Kingdom Reborn     526
Dark Empire        523
Zombie Outbreak    517
Shadow Protocol    515
Ninja Legacy       508
City Builder X     503
Ocean Explorer     503
Neon Drift         499
Street Legends     498
Galaxy Raiders     490
Battle Arena       488
Space Colony       485
Warzone Echo       482
Cyber Frontier     482
Football Pro       478
Fantasy League     474
Dragon Realm       469
Tactical Strike    464
Name: count, dtype: int64

In [23]:
df["Genre"].value_counts(dropna=False)

Genre
Racing        1039
Fighting      1038
Simulation    1023
Puzzle        1012
Sports         980
Shooter        974
Strategy       973
RPG            950
Adventure      949
Action         932
NaN             79
action          30
Action          21
Name: count, dtype: int64

In [24]:
df["Genre"]=df["Genre"].str.strip().str.title()

In [25]:
df["Genre"].value_counts(dropna=False)

Genre
Racing        1039
Fighting      1038
Simulation    1023
Puzzle        1012
Action         983
Sports         980
Shooter        974
Strategy       973
Rpg            950
Adventure      949
NaN             79
Name: count, dtype: int64

In [26]:
df['Genre'].isna().sum()

np.int64(79)

In [27]:
df["Genre"]=df["Genre"].fillna("N/a")

In [28]:
df["Genre"].value_counts(dropna=False)

Genre
Racing        1039
Fighting      1038
Simulation    1023
Puzzle        1012
Action         983
Sports         980
Shooter        974
Strategy       973
Rpg            950
Adventure      949
N/a             79
Name: count, dtype: int64

In [29]:
df["Publisher"].value_counts(dropna=False)

Publisher
Activision                        954
Capcom                            925
Bandai Namco                      921
Microsoft                         912
Ubisoft                           904
Electronic Arts                   901
Square Enix                       895
SEGA                              884
Take-Two Interactive              882
Nintendo                          873
Sony Interactive Entertainment    849
NaN                               100
Name: count, dtype: int64

In [30]:
df["Publisher"]=df["Publisher"].str.strip().str.title()

In [31]:
df["Publisher"].value_counts(dropna=False)

Publisher
Activision                        954
Capcom                            925
Bandai Namco                      921
Microsoft                         912
Ubisoft                           904
Electronic Arts                   901
Square Enix                       895
Sega                              884
Take-Two Interactive              882
Nintendo                          873
Sony Interactive Entertainment    849
NaN                               100
Name: count, dtype: int64

In [32]:
df["Publisher"]=df["Publisher"].fillna(0)

In [33]:
df["Publisher"].value_counts(dropna=False)

Publisher
Activision                        954
Capcom                            925
Bandai Namco                      921
Microsoft                         912
Ubisoft                           904
Electronic Arts                   901
Square Enix                       895
Sega                              884
Take-Two Interactive              882
Nintendo                          873
Sony Interactive Entertainment    849
0                                 100
Name: count, dtype: int64

In [34]:
df["Developer"].value_counts(dropna=False)

Developer
Blue Horizon          1040
Nova Games            1025
NextGen Labs          1014
Quantum Works         1009
Studio Alpha          1008
Vertex Studio          995
Iron Wolf              991
Pixel Forge            982
Red Dragon Studios     978
Digital Realm          958
Name: count, dtype: int64

In [35]:
df["Developer"]=df["Developer"].str.strip().str.title()

In [36]:
df["Developer"].value_counts(dropna=False)

Developer
Blue Horizon          1040
Nova Games            1025
Nextgen Labs          1014
Quantum Works         1009
Studio Alpha          1008
Vertex Studio          995
Iron Wolf              991
Pixel Forge            982
Red Dragon Studios     978
Digital Realm          958
Name: count, dtype: int64

In [37]:
df['Region'].value_counts(dropna=False)

Region
North America           1735
Latin America           1700
Japan                   1687
Europe                  1645
Middle East & Africa    1631
Asia-Pacific            1602
Name: count, dtype: int64

In [38]:
df["Region"]=df["Region"].str.strip().str.title()

In [39]:
df['Region'].value_counts(dropna=False)

Region
North America           1735
Latin America           1700
Japan                   1687
Europe                  1645
Middle East & Africa    1631
Asia-Pacific            1602
Name: count, dtype: int64

In [40]:
df["Sales_Channel"].value_counts(dropna=False)

Sales_Channel
Retail                2036
Subscription          2009
Digital Store         2004
Online Marketplace    1980
Mobile Store          1951
digital store           20
Name: count, dtype: int64

In [41]:
df["Sales_Channel"]=df["Sales_Channel"].str.strip().str.title()

In [42]:
df["Sales_Channel"].value_counts(dropna=False)

Sales_Channel
Retail                2036
Digital Store         2024
Subscription          2009
Online Marketplace    1980
Mobile Store          1951
Name: count, dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Game_ID           10000 non-null  object
 1   Game_Title        10000 non-null  object
 2   Release_Date      9880 non-null   datetime64[ns]
 3   Platform          10000 non-null  object
 4   Genre             10000 non-null  object
 5   Publisher         10000 non-null  object
 6   Developer         10000 non-null  object
 7   Region            10000 non-null  object
 8   Age_Rating        10000 non-null  object
 9   Sales_Channel     10000 non-null  object
 10  Units_Sold_M      10000 non-null  float64
 11  Avg_Price_USD     10000 non-null  float64
 12  Discount_Pct      10000 non-null  float64
 13  User_Score        9850 non-null   float64
 14  Metacritic_Score  9900 non-null   float64
 15  Global_Revenue_M  10000 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(9)
memory usage: 1.2+ MB

In [44]:
df.isnull().sum()

Game_ID               0
Game_Title            0
Release_Date        120
Platform              0
Genre                 0
Publisher             0
Developer             0
Region                0
Age_Rating            0
Sales_Channel         0
Units_Sold_M          0
Avg_Price_USD         0
Discount_Pct          0
User_Score          150
Metacritic_Score    100
Global_Revenue_M      0
dtype: int64

In [45]:
df[df["Release_Date"].isnull()]

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
199,Gm100199,Battle Arena,NaT,Ps5,Sports,Ubisoft,Nextgen Labs,Japan,E,Retail,1.14,79.62,29.7,3.2,57.0,63.81
271,Gm100271,Dragon Realm,NaT,Ps4,Racing,Take-Two Interactive,Nextgen Labs,Latin America,E10+,Subscription,0.97,67.51,22.7,7.0,95.0,50.62
278,Gm100278,Warzone Echo,NaT,Xbox One,Adventure,Ubisoft,Nextgen Labs,North America,T,Online Marketplace,10.37,68.79,0.6,6.7,91.0,709.07
301,Gm100301,Street Legends,NaT,Pc,Racing,Activision,Iron Wolf,Latin America,T,Retail,1.02,48.56,56.8,3.1,50.0,21.40
433,Gm100433,Tactical Strike,NaT,Xbox One,Simulation,Nintendo,Iron Wolf,Europe,E10+,Mobile Store,1.56,79.79,13.7,6.2,96.0,107.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9686,Gm109686,Fantasy League,NaT,Ps4,Rpg,Capcom,Studio Alpha,Middle East & Africa,E10+,Digital Store,6.68,35.66,28.7,5.3,84.0,169.84
9728,Gm109728,Ocean Explorer,NaT,Pc,Sports,Bandai Namco,Iron Wolf,North America,T,Retail,2.24,49.76,52.2,6.1,95.0,53.28
9809,Gm109809,Neon Drift,NaT,Ps4,Action,Electronic Arts,Quantum Works,Latin America,M,Subscription,1.29,61.62,23.0,7.5,48.0,61.21
9872,Gm109872,Mystic Quest,NaT,Ps5,Sports,Take-Two Interactive,Iron Wolf,Asia-Pacific,T,Subscription,0.33,24.06,60.4,5.2,52.0,3.14
9904,Gm109904,Warzone Echo,NaT,Ps4,Shooter,Ubisoft,Studio Alpha,Middle East & Africa,E10+,Mobile Store,1.67,48.39,1.6,5.2,71.0,79.52

In [46]:
df[df["User_Score"].isnull()]

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
38,Gm100038,Ocean Explorer,2018-12-08,Xbox One,Action,Sony Interactive Entertainment,Blue Horizon,Latin America,RP,Online Marketplace,0.12,68.83,14.1,NaN,96.0,7.09
56,Gm100056,Fantasy League,2021-03-24,Ps4,Sports,Capcom,Nextgen Labs,Middle East & Africa,E,Retail,0.12,42.23,22.8,NaN,94.0,3.91
150,Gm100150,Dragon Realm,2024-09-12,Xbox One,Shooter,Activision,Blue Horizon,Europe,RP,Digital Store,1.71,60.15,5.4,NaN,98.0,97.30
286,Gm100286,Galaxy Raiders,2017-09-17,Steam Deck,Fighting,Microsoft,Pixel Forge,Latin America,RP,Mobile Store,0.33,66.14,58.2,NaN,49.0,9.12
366,Gm100366,Kingdom Reborn,2019-08-26,Steam Deck,Fighting,Electronic Arts,Vertex Studio,Europe,T,Retail,0.32,37.25,15.8,NaN,81.0,10.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9664,Gm109664,Battle Arena,2016-08-25,Steam Deck,Puzzle,Take-Two Interactive,Pixel Forge,Latin America,E,Digital Store,1.72,24.17,6.2,NaN,57.0,38.99
9712,Gm109712,Racing Horizon,2016-07-07,Xbox Series X,Action,Sega,Digital Realm,Europe,E10+,Subscription,0.25,50.36,17.2,NaN,83.0,10.42
9916,Gm109916,Ocean Explorer,2025-11-05,Ps5,Fighting,Nintendo,Vertex Studio,Middle East & Africa,RP,Retail,1.24,57.65,11.0,NaN,65.0,63.62
9927,Gm109927,Zombie Outbreak,2016-09-16,Xbox One,Action,Microsoft,Nextgen Labs,Latin America,RP,Subscription,0.34,64.98,57.0,NaN,40.0,9.50
9961,Gm102587,Racing Horizon,2016-06-16,Xbox One,Fighting,Ubisoft,Nova Games,North America,M,Digital Store,7.39,53.58,7.1,NaN,47.0,367.84

In [47]:
df["User_Score"].median()

6.0

In [48]:
df["User_Score"]=df["User_Score"].fillna(
                                df["User_Score"].median())

In [49]:
df.isnull().sum()

Game_ID               0
Game_Title            0
Release_Date        120
Platform              0
Genre                 0
Publisher             0
Developer             0
Region                0
Age_Rating            0
Sales_Channel         0
Units_Sold_M          0
Avg_Price_USD         0
Discount_Pct          0
User_Score            0
Metacritic_Score    100
Global_Revenue_M      0
dtype: int64

In [50]:
df["Metacritic_Score"].median()

66.0

In [51]:
df["Metacritic_Score"]=df["Metacritic_Score"].fillna(
                           df["Metacritic_Score"].median() 
)

In [52]:
df.isnull().sum()

Game_ID               0
Game_Title            0
Release_Date        120
Platform              0
Genre                 0
Publisher             0
Developer             0
Region                0
Age_Rating            0
Sales_Channel         0
Units_Sold_M          0
Avg_Price_USD         0
Discount_Pct          0
User_Score            0
Metacritic_Score      0
Global_Revenue_M      0
dtype: int64

In [53]:
df.duplicated().sum()

np.int64(50)

In [54]:
df[df.duplicated(keep=False)]

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
42,Gm100042,Dark Empire,2020-02-06,Xbox Series X,Adventure,Bandai Namco,Blue Horizon,Asia-Pacific,RP,Digital Store,3.27,73.43,3.0,8.7,79.0,232.91
177,Gm100177,Dark Empire,2022-05-07,Pc,Puzzle,Microsoft,Iron Wolf,Europe,T,Online Marketplace,8.71,33.83,46.8,7.4,63.0,156.76
418,Gm100418,Ninja Legacy,2016-06-20,Ps5,Racing,Sega,Red Dragon Studios,Japan,T,Digital Store,1.69,49.63,34.6,8.5,40.0,54.85
438,Gm100438,Ninja Legacy,2024-04-09,Xbox One,Puzzle,Microsoft,Quantum Works,North America,E,Digital Store,0.35,62.92,56.1,9.4,64.0,9.67
533,Gm100533,Racing Horizon,2020-01-15,Pc,Shooter,Activision,Quantum Works,Middle East & Africa,RP,Retail,5.52,55.99,22.5,9.1,43.0,239.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Gm107872,Football Pro,2016-12-30,Nintendo Switch,Puzzle,Microsoft,Quantum Works,Japan,T,Digital Store,1.43,49.98,18.7,6.1,58.0,58.11
9996,Gm100533,Racing Horizon,2020-01-15,Pc,Shooter,Activision,Quantum Works,Middle East & Africa,RP,Retail,5.52,55.99,22.5,9.1,43.0,239.53
9997,Gm109895,Tactical Strike,2019-09-16,Mobile,Shooter,Sega,Nextgen Labs,North America,RP,Digital Store,0.35,16.20,22.1,2.7,83.0,4.42
9998,Gm107494,Cyber Frontier,2019-06-15,Mobile,Rpg,Microsoft,Red Dragon Studios,North America,M,Retail,0.34,38.16,6.6,5.9,55.0,12.12
9999,Gm105747,Tactical Strike,2022-05-27,Pc,Action,Activision,Quantum Works,Middle East & Africa,M,Retail,0.40,16.89,40.0,4.2,92.0,4.05

In [55]:
df = df.drop_duplicates()

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df.shape

(9950, 16)

In [200]:
df.dtypes

Game_ID                     object
Game_Title                  object
Release_Date        datetime64[ns]
Platform                    object
Genre                       object
Publisher                   object
Developer                   object
Region                      object
Age_Rating                  object
Sales_Channel               object
Units_Sold_M               float64
Avg_Price_USD              float64
Discount_Pct               float64
User_Score                 float64
Metacritic_Score           float64
Global_Revenue_M           float64
dtype: object

In [201]:
df[df["User_Score"] > 10]

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
485,Gm100485,Cyber Frontier,2018-10-26,Steam Deck,Simulation,Sony Interactive Entertainment,Pixel Forge,Latin America,RP,Online Marketplace,9.83,65.45,19.2,15.0,88.0,519.85
2315,Gm102315,Shadow Protocol,2025-10-02,Mobile,Racing,Electronic Arts,Quantum Works,Europe,E,Online Marketplace,2.04,24.59,45.7,15.0,48.0,27.24
3736,Gm103736,Shadow Protocol,2019-03-02,Xbox One,Sports,Nintendo,Nova Games,Asia-Pacific,E10+,Mobile Store,0.34,49.14,41.0,15.0,73.0,9.86
4960,Gm104960,Ocean Explorer,2017-12-20,Pc,Shooter,Bandai Namco,Red Dragon Studios,Asia-Pacific,E10+,Retail,2.00,46.28,3.5,15.0,60.0,89.32
6096,Gm106096,Mystic Quest,2017-06-25,Ps5,Rpg,Bandai Namco,Quantum Works,Asia-Pacific,E10+,Online Marketplace,1.46,41.59,52.5,15.0,48.0,28.84
7252,Gm107252,Football Pro,2015-03-15,Mobile,Sports,Take-Two Interactive,Iron Wolf,Europe,E,Retail,1.24,73.21,58.6,15.0,45.0,37.58
7995,Gm107995,Kingdom Reborn,2016-10-11,Ps5,Rpg,Capcom,Studio Alpha,Latin America,T,Retail,0.54,71.98,59.3,15.0,39.0,15.82
9224,Gm109224,Racing Horizon,2017-12-24,Nintendo Switch,Puzzle,Capcom,Nextgen Labs,Latin America,E,Digital Store,1.58,35.83,64.7,15.0,85.0,19.98
9445,Gm109445,Galaxy Raiders,2022-06-23,Ps5,Adventure,Square Enix,Red Dragon Studios,Middle East & Africa,M,Online Marketplace,0.63,72.78,53.9,15.0,70.0,21.14
9470,Gm109470,Tactical Strike,2022-10-16,Xbox One,Puzzle,Sega,Red Dragon Studios,Europe,RP,Online Marketplace,0.98,65.71,60.0,15.0,48.0,25.76

In [58]:
df.loc[df["User_Score"]>10,"User_Score"]=pd.NA

In [60]:
df[df["User_Score"] > 9.5]

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
27,Gm100027,Neon Drift,2017-11-15,Mobile,Adventure,Nintendo,Studio Alpha,Asia-Pacific,T,Retail,0.85,72.73,15.0,9.9,62.0,52.55
35,Gm100035,Warzone Echo,2023-09-24,Ps4,Sports,Bandai Namco,Quantum Works,Latin America,RP,Retail,2.85,72.65,62.1,9.6,95.0,78.47
46,Gm100046,Dark Empire,2020-06-07,Xbox One,Sports,Square Enix,Studio Alpha,Japan,M,Subscription,0.79,29.16,29.4,9.6,36.0,16.26
151,Gm100151,Space Colony,2023-11-18,Xbox One,Fighting,Bandai Namco,Red Dragon Studios,Latin America,RP,Online Marketplace,0.72,50.44,58.9,9.6,61.0,14.93
169,Gm100169,Ocean Explorer,2024-06-27,Xbox Series X,Shooter,Bandai Namco,Vertex Studio,Middle East & Africa,E,Online Marketplace,0.89,74.72,9.4,9.8,72.0,60.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9887,Gm109887,Ocean Explorer,2020-01-14,Xbox Series X,Racing,Electronic Arts,Red Dragon Studios,Japan,T,Mobile Store,0.57,15.45,43.2,9.9,92.0,5.00
9912,Gm109912,Ninja Legacy,2017-10-25,Ps4,Puzzle,Sony Interactive Entertainment,Blue Horizon,Asia-Pacific,E10+,Mobile Store,0.96,48.79,49.9,9.6,98.0,23.47
9924,Gm109924,Space Colony,2019-07-04,Xbox One,Strategy,Capcom,Blue Horizon,Japan,E10+,Subscription,1.60,64.28,26.1,9.6,39.0,76.00
9945,Gm109945,Football Pro,2023-06-20,Nintendo Switch,Racing,Square Enix,Red Dragon Studios,Europe,RP,Retail,0.37,64.61,32.4,9.6,82.0,16.16
9947,Gm109947,Tactical Strike,2023-08-24,Ps5,Racing,Electronic Arts,Quantum Works,Latin America,RP,Retail,0.17,43.82,11.7,9.7,58.0,6.58

In [62]:
df[df["Metacritic_Score"] > 100]

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
2987,Gm102987,Zombie Outbreak,2016-03-01,Xbox One,Adventure,Activision,Vertex Studio,Asia-Pacific,E10+,Subscription,1.93,17.78,34.0,8.8,110.0,22.65
3458,Gm103458,Kingdom Reborn,2015-04-14,Ps5,Sports,Electronic Arts,Nextgen Labs,North America,RP,Online Marketplace,7.75,69.81,21.9,5.9,110.0,422.54
5089,Gm105089,Space Colony,2017-07-23,Ps5,Sports,Nintendo,Pixel Forge,Japan,E10+,Online Marketplace,0.97,48.62,26.4,5.3,110.0,34.71
5366,Gm105366,Kingdom Reborn,2022-11-17,Ps4,Sports,Activision,Nova Games,Middle East & Africa,E10+,Retail,0.48,56.43,33.6,5.2,110.0,17.99
7265,Gm107265,Street Legends,2018-06-25,Nintendo Switch,Shooter,Capcom,Vertex Studio,Japan,E,Mobile Store,2.75,64.15,56.5,2.6,110.0,76.74
7462,Gm107462,Kingdom Reborn,2019-03-01,Xbox One,Racing,Sony Interactive Entertainment,Nextgen Labs,Latin America,E,Mobile Store,5.92,76.51,61.5,6.0,110.0,174.38
7894,Gm107894,Mystic Quest,2017-10-18,Ps5,Shooter,Take-Two Interactive,Studio Alpha,North America,RP,Digital Store,0.43,51.81,37.0,6.2,110.0,14.04
8066,Gm108066,Football Pro,2025-07-14,Xbox One,Fighting,Ubisoft,Quantum Works,North America,RP,Mobile Store,0.65,29.31,26.5,4.7,110.0,14.00
8359,Gm108359,Battle Arena,2015-09-29,Ps5,Puzzle,Sega,Nova Games,Latin America,RP,Retail,0.47,64.19,20.9,3.4,110.0,23.86
8684,Gm108684,Space Colony,2017-09-08,Xbox Series X,Adventure,Ubisoft,Nextgen Labs,Latin America,E,Retail,1.39,55.33,67.4,5.3,110.0,25.07

In [63]:
df.loc[df["Metacritic_Score"]>100,"Metacritic_Score"]=pd.NA

In [65]:
df.isnull().sum()

Game_ID               0
Game_Title            0
Release_Date        120
Platform              0
Genre                 0
Publisher             0
Developer             0
Region                0
Age_Rating            0
Sales_Channel         0
Units_Sold_M          0
Avg_Price_USD         0
Discount_Pct          0
User_Score           10
Metacritic_Score     10
Global_Revenue_M      0
dtype: int64

In [66]:
df[df["Discount_Pct"]>100]

,Game_ID,Game_Title,Release_Date,Platform,Genre,Publisher,Developer,Region,Age_Rating,Sales_Channel,Units_Sold_M,Avg_Price_USD,Discount_Pct,User_Score,Metacritic_Score,Global_Revenue_M
299,Gm100299,Galaxy Raiders,2024-01-03,Xbox One,Shooter,Sony Interactive Entertainment,Nova Games,Middle East & Africa,E10+,Mobile Store,3.19,24.59,125.0,8.9,73.0,-19.61
1926,Gm101926,Mystic Quest,2018-12-23,Ps4,Adventure,Capcom,Nova Games,Latin America,T,Online Marketplace,0.20,21.14,125.0,9.0,82.0,-1.06
2566,Gm102566,Street Legends,2021-06-05,Xbox Series X,Strategy,Microsoft,Nova Games,Asia-Pacific,M,Mobile Store,12.32,46.69,125.0,5.7,85.0,-143.81
4151,Gm104151,Neon Drift,2015-04-28,Steam Deck,Rpg,Capcom,Vertex Studio,Asia-Pacific,M,Mobile Store,1.14,42.25,125.0,8.1,91.0,-12.04
4183,Gm104183,Dark Empire,2022-12-22,Pc,Simulation,Capcom,Iron Wolf,Latin America,E10+,Subscription,0.66,76.63,125.0,8.7,53.0,-12.64
5084,Gm105084,Ocean Explorer,2023-10-12,Nintendo Switch,Racing,Capcom,Pixel Forge,Latin America,T,Digital Store,2.41,62.71,125.0,9.8,81.0,-37.78
5514,Gm105514,City Builder X,2016-11-20,Mobile,Strategy,Bandai Namco,Studio Alpha,Japan,E10+,Retail,1.07,77.44,125.0,7.3,80.0,-20.72
6541,Gm106541,Battle Arena,2025-10-16,Mobile,Sports,Bandai Namco,Quantum Works,Middle East & Africa,M,Retail,0.63,62.26,125.0,2.9,35.0,-9.81
9440,Gm109440,Galaxy Raiders,2025-03-04,Pc,Sports,Sony Interactive Entertainment,Quantum Works,Asia-Pacific,E10+,Retail,1.17,70.59,125.0,7.2,44.0,-20.65
9841,Gm109841,Racing Horizon,2020-01-17,Xbox One,Simulation,Bandai Namco,Red Dragon Studios,Middle East & Africa,RP,Digital Store,0.99,66.23,125.0,6.6,55.0,-16.39

In [67]:
df.loc[df["Discount_Pct"]>100,"Discount_Pct"]=pd.NA

In [68]:
df.isnull().sum()

Game_ID               0
Game_Title            0
Release_Date        120
Platform              0
Genre                 0
Publisher             0
Developer             0
Region                0
Age_Rating            0
Sales_Channel         0
Units_Sold_M          0
Avg_Price_USD         0
Discount_Pct         10
User_Score           10
Metacritic_Score     10
Global_Revenue_M      0
dtype: int64

In [69]:
df["Discount_Pct"].median()

35.1

In [70]:
df['Discount_Pct']=df['Discount_Pct'].fillna(
    df["Discount_Pct"].median()
)

In [71]:
df['User_Score'].median()

6.0

In [72]:
df['User_Score']=df['User_Score'].fillna(
    df["User_Score"].median()
)

In [73]:
df['Metacritic_Score'].median()

66.0

In [74]:
df['Metacritic_Score']=df['Metacritic_Score'].fillna(
    df["Metacritic_Score"].median()
)

In [76]:
df.isnull().sum()

Game_ID               0
Game_Title            0
Release_Date        120
Platform              0
Genre                 0
Publisher             0
Developer             0
Region                0
Age_Rating            0
Sales_Channel         0
Units_Sold_M          0
Avg_Price_USD         0
Discount_Pct          0
User_Score            0
Metacritic_Score      0
Global_Revenue_M      0
dtype: int64

In [79]:
df.to_excel('Video_Game_Sales_data.xlsx',index=False)

In [80]:
print("Cleaned data saved successfully!")

Cleaned data saved successfully!